### ISSUE TITLE
Docker run error 

### ISSUE THREAD

**Issue by CaiJiJi** [blakebjorn/opennodes#2]
```
opennodes-crawler     | /bin/sh: dash-cli: not found
opennodes-crawler     | Traceback (most recent call last):
opennodes-crawler     |   File "//crawler.py", line 865, in <module>
opennodes-crawler     |     main(seed=True)
opennodes-crawler     |   File "//crawler.py", line 688, in main
opennodes-crawler     |     mnodes = update_masternode_list()
opennodes-crawler     |   File "//crawler.py", line 439, in update_masternode_list
opennodes-crawler     |     masternodes = json.loads(masternodes)
opennodes-crawler     |   File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
opennodes-crawler     |     return _default_decoder.decode(s)
opennodes-crawler     |   File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
opennodes-crawler     |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
opennodes-crawler     |   File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
opennodes-crawler     |     raise JSONDecodeError("Expecting value", s, err.value) from None
opennodes-crawler     | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by blakebjorn** [comment]
Can't connect to the Dash node. noticed the default config was not pointing to the correct host, so if you repull from master and double check all the values in your `.env` it should work. The crawler container runs on the host network so all connections to the other containers need to be via localhost and not the docker service name
